language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"

os:
  - linux
  - osx

branches:
  except:
    - /^v[0-9]/

before_install:
  - echo $TRAVIS_OS_NAME
  - echo $TRAVIS_PYTHON_VERSION
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi

install:
  - pip install -U -r requirements-test.txt

before_script:
  - if [ "$TRAVIS_PYTHON_VERSION" == "pypy3" ]; then pip install mock; fi

script:
  - make travis

after_success:
  - coveralls

matrix:
  fast_finish: true
  allow_failures:
    - os: osx
