language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"

os:
  - linux
#  - osx

branches:
  only:
    - master
    - release

before_install:
  - echo Travis OS Name ... ${TRAVIS_OS_NAME}
  - echo Travis Python .... ${TRAVIS_PYTHON_VERSION}

install:
  - pip install --upgrade pip
  - pip install --upgrade --requirement requirements-test.txt

script:
  - if [ ${TRAVIS_PYTHON_VERSION} == "nightly" ]; then
      make travis-nightly;
    else
      make travis;
    fi

after_success:
  - coveralls

matrix:
  fast_finish: true
  allow_failures:
    - os: osx
    - python: "nightly"
