language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"

os:
  - linux
#  - osx

addons:
  apt:
    packages:
    - python3-dev

branches:
  only:
    - master
    - release

before_install:
  - echo Travis OS Name ... ${TRAVIS_OS_NAME}
  - echo Travis Python .... ${TRAVIS_PYTHON_VERSION}
  - echo Python Version ... $(python --version)

install:
  - pip install --upgrade pip
  - pip install --upgrade --requirement requirements-test.txt

script:
  - if [ ${TRAVIS_PYTHON_VERSION} != "nightly" ]; then make travis; fi
  - if [ ${TRAVIS_PYTHON_VERSION} == "nightly" ]; then make travis-nightly; fi

after_success:
  - coveralls

matrix:
  fast_finish: true
  allow_failures:
    - os: osx
