language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"

branches:
  except:
    - /^v[0-9]/

install:
  - pip install -U -r requirements-test.txt

script:
  - make travis

after_success:
  - coveralls
