language: python

python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - pip install -U -r requirements-test.txt
  - if [[ $TRAVIS_PYTHON_VERSION == "3.2" ]]; then pip install coverage==3.7.1; fi

script:
  - make test
  - make pep8

after_success:
  - coveralls
